eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/       #指定服务注册中心

server:
  port: 8769

spring:
  application:
    name: com.zr.service-zuul


zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: com.zr.service-ribbon
    api-b:
      path: /api-b/**
      serviceId: com.zr.service-feign